version: ~> 1.0

os: linux

dist: xenial

language: python

python:
    - 3.7
    - 3.8

before_install:
    # define variables
    - name=hijinks
    - contents=$TRAVIS_BUILD_DIR/$name

    # install lilypond:
    - lilypond=/tmp/lilypond
    - lilypond_url=http://lilypond.org/download/binaries/linux-64/
    - lilypond_source=lilypond-2.19.84-1.linux-64.sh
    - wget -q -O $lilypond $lilypond_url/$lilypond_source
    - sh $lilypond --batch

    # clone & install abjad dev branch:
    - abjad=/tmp/abjad
    - git clone -b trevor/dev https://github.com/Abjad/abjad.git $abjad
    - pip install $abjad
    - export MYPYPATH=$abjad

    # clone & install rmakers:
    - rmakers=/tmp/abjad-ext-rmakers
    - git clone https://github.com/Abjad/abjad-ext-rmakers.git $rmakers
    - pip install $rmakers
    - export MYPYPATH=$MYPYPATH:$rmakers

    # clone & install baca:
    - baca=/tmp/baca
    - git clone https://github.com/trevorbaca/baca.git $baca
    - pip install $baca
    - export MYPYPATH=$MYPYPATH:$baca

    # symlink to mypy configfile
    - ln -s $baca/dotfiles/mypy.ini ~/.mypy.ini

    # clone & install baca test:
    - test=/tmp/test
    - git clone https://github.com/trevorbaca/test.git $test
    
    # symlink to baca test
    - unlink $contents/test.py
    - ln -s $test/test_segments.py $contents/test.py

    # clone & install ide:
    - ide=/tmp/ide
    - git clone https://github.com/Abjad/ide.git $ide
    - pip install $ide
    - export MYPYPATH=$MYPYPATH:$ide
    - export PATH=$PATH:$ide/ide/scr

    # log environment variables
    - echo $MYPYPATH
    - echo $PATH
    - echo $PYTHONPATH
    - echo $TRAVIS_BUILD_DIR

    # log present working directory
    - pwd
    - ls

install:
    - pip install -e .
    # - prime-parser-tables

    # log versions
    - black --version
    - flake8 --version
    - isort --version
    - mypy --version
    - pytest --version

script:
    - $baca/scr/black-check $contents
    - $baca/scr/flake8-check $contents
    - $baca/scr/isort-check $contents
    - mypy $contents
    - $baca/scr/baca-doctest $contents
    - py.test -rf $contents/test.py

notifications:
    email: false
